version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    open-pull-requests-limit: 0 # security updates only
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
